"""initial schema

Revision ID: 71e32f4d396e
Revises: 
Create Date: 2026-07-29 19:28:03.908234

"""
from alembic import op
import sqlalchemy as sa


revision = '71e32f4d396e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('benchmark_1', sa.String(length=16), nullable=False),
    sa.Column('benchmark_2', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bootstrap_state',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('hydrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_open', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_bar')
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_bars_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_bars_ticker'), ['ticker'], unique=False)

    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=False),
    sa.Column('symbols_ok', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol_sync_state',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('last_success_date', sa.Date(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('corporate_actions_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('model_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('target_weight_pct', sa.Float(), nullable=False),
    sa.Column('target_dollars', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', name='uq_target')
    )
    with op.batch_alter_table('model_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_targets_ticker'), ['ticker'], unique=False)

    op.create_table('official_fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fill_date', sa.Date(), nullable=False),
    sa.Column('official_open', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', 'fill_date', name='uq_fill')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL', 'FEE', 'SPLIT', 'SYMBOL_CHANGE', name='transactiontype'), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('cash_flow', sa.Float(), nullable=True),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.Column('new_ticker', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', name='uq_txn_source_key')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_ticker'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    op.drop_table('official_fills')
    with op.batch_alter_table('model_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_targets_ticker'))

    op.drop_table('model_targets')
    op.drop_table('symbol_sync_state')
    op.drop_table('refresh_runs')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_bars_ticker'))
        batch_op.drop_index(batch_op.f('ix_price_bars_date'))

    op.drop_table('price_bars')
    op.drop_table('bootstrap_state')
    op.drop_table('accounts')
    # ### end Alembic commands ###
